export { default as HeroBg } from "./HeroBg1.jpg";
export { default as mainType } from "./mainType1.png";
export { default as logo } from "./Logo.png";
export { default as cutout1 } from "./cutouts/cutout1.png";
export { default as cutout2 } from "./cutouts/cutout2.png";
export { default as cutout3 } from "./cutouts/cutout3.png";
export { default as cutout4 } from "./cutouts/cutout4.png";
export { default as cutout5 } from "./cutouts/cutout5.png";
export { default as cutout6 } from "./cutouts/cutout6.png";
export { default as cutout7 } from "./cutouts/cutout7.png";
export { default as cutout8 } from "./cutouts/cutout8.png";
export { default as flybot } from "./cutouts/flybot.png";
export { default as flybot1 } from "./cutouts/flybot1.png";
export { default as community1 } from "./cutouts/community1.png";
export { default as community2 } from "./cutouts/community2.png";
export { default as float1 } from "./cutouts/float1.png";
export { default as float2 } from "./cutouts/float2.png";
export { default as TopBg } from "./TopBg.jpeg";
export { default as About1 } from "./About1.jpg";
export { default as CommunityBg } from "./CommunityBg.jpg";
export { default as CommunityBg1 } from "./CommunityBg1.jpg";
export { default as bg } from "./bg.jpg";
export { default as bg2 } from "./Bg2.jpg";
export { default as bg3 } from "./Bg3.jpg";
export { default as bg4 } from "./Bg4.jpg";
export { default as bg5 } from "./Bg5.jpg";
export { default as suiOnCampus } from "./suiO.jpeg";
export { default as teamSpark } from "./teamspark.jpg";
export { default as gmfi } from "./gmfi.jpg";
export { default as stars } from "./stars.png";
export { default as twinkling } from "./twinkling.png";

export { default as createBg } from "./createBg.jpg";

export { default as arena1 } from "./arena1.jpg";
export { default as arena2 } from "./arena2.jpg";
export { default as arena3 } from "./arena3.jpg";
export { default as arena4 } from "./arena4.jpg";
export { default as arena5 } from "./arena5.jpg";
export { default as arena6 } from "./arena6.jpg";
export { default as arena7 } from "./arena7.jpg";
export { default as arena8 } from "./arena8.jpg";
// export { default as arena9 } from "./arena9.jpg";
// export { default as arena10 } from "./arena10.jpg";
